
[webserver]
port = ":19089"

# 缓存配置（显著提升重复请求性能）
[cache]
type = "file"               # 使用文件缓存
basepath = "/var/cache/tegola"  # 缓存目录（确保有写入权限）
max_age = "72h"             # 缓存过期时间（72小时）
max_size = 10737418240      # 最大缓存大小（10GB）

# PostGIS数据提供者配置
[[providers]]
name = "inference_database" # 数据源名称（唯一标识）
type = "mvt_postgis"            # 数据源类型      # 数据源类型
uri = "postgres://postgres:postgres@10.13.1.13:5432/inference_database?sslmode=disable"
srid = 3857               # 输出瓦片的投影（Web Mercator）
params = ["taskId"]

# 启用连接池复用
pool_min_idle = 5
pool_max_idle = 20
pool_max_lifetime = "300s"
# 地面图层配置
# 建筑物图层配置
[[providers.layers]]
name = "!TASKID!"
geometry_fieldname = "geometry"
geometry_type = "multipolygon"
id_fieldname = "id"
srid = 3857
params = ["taskId"]

sql = """
SELECT ST_AsMVTGeom(geometry, !BBOX!, 4096, 256, true) AS geometry, id, !COLUMNS!
FROM !TASKID!
WHERE geometry && !BBOX!
"""

# 地图配置
[[maps]]
name = "inference_database"     # 地图名称（用于URL：/maps/inference_database）
attribution = "Tegola Vector Tiles"  # 版权信息


# 配置地图参数
[[maps.params]]
name = "taskId"
token = "!TASKID!"
type = "string"

# 地图中的动态图层
[[maps.layers]]
provider_layer = "inference_database.!TASKID!"

