name: tegola-upload-path
description: "returns the correct upload path for os"
inputs:
  name:
    description: "base dir name"
    default: "tegola"
    required: false

outputs:
  dir-path:
    description: "dir path for tegola"
    value: ${{ steps.compute-path.outputs.dir-path }}

runs:
  using: "composite"
  steps:
    - name: set env (not Windows)
      if: ${{ runner.os != 'Windows' }}
      run: echo "TEGOLA_PATH=cmd/${{inputs.name}}/" >> $GITHUB_ENV
      shell: bash

    - name: set env (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: echo "TEGOLA_PATH=cmd\\${{inputs.name}}\\" >> $GITHUB_ENV
      shell: bash

    - id: compute-path
      run: echo "dir-path=${TEGOLA_PATH}" >> $GITHUB_OUTPUT
      shell: bash
